- platform: mjpeg
  name: Front gate
  mjpeg_url: http://10.163.205.76:8081
  still_image_url: http://10.163.205.76/picture/1/current/?_username=admin&_signature=e3f5066aeb0936998e814d130aa77cdf70667f5d
  authentication: basic
  username: !secret cctv_username
  password: !secret cctv_password
- platform: mjpeg
  name: Front door apartment
  mjpeg_url: http://10.163.205.76:8082
  still_image_url: http://10.163.205.76/picture/2/current/?_username=admin&_signature=d81982a468a76bee5a58282bade0efd3e3f736b5
  authentication: basic
  username: !secret cctv_username
  password: !secret cctv_password
- platform: mjpeg
  name: Backyard
  mjpeg_url: http://10.163.205.76:8083
  still_image_url: http://10.163.205.76/picture/3/current/?_username=admin&_signature=9965e229dce9c814625dcca79b7d5c52198f8cae
  authentication: basic
  username: !secret cctv_username
  password: !secret cctv_password
