
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  external_url: !secret url
  internal_url: !secret url
  allowlist_external_dirs:
    - '/config/tmp'
  
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret proxy_host
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml

light: !include_dir_merge_list  lights
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
cover: !include_dir_merge_list covers

python_script:

# Text to speech
tts:
  - platform: google_translate

recorder:
  exclude: !include recorder_exclude.yaml

influxdb:
  host: localhost
  port: 8086
  database: hass
  username: hass
  password: hass
  max_retries: 3
  default_measurement: state
  exclude: !include recorder_exlcude.yaml

binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: Washing machine
        value_template: >
          {{ states("sensor.washing_machine_power") | float(0) > 12 }}
        delay_off: "00:10:00"
        icon_template: >
          {% if is_state("binary_sensor.washing_machine", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
      outside_motion:
        friendly_name: Outside motion
        value_template: >
          {{ 
              'person' in states("sensor.cctv_motion_detection") 
              or 'bicycle' in states("sensor.cctv_motion_detection") 
              or 'car' in states("sensor.cctv_motion_detection") 
              or 'truck' in states("sensor.cctv_motion_detection") 
              or 'lwa' in states("sensor.cctv_motion_detection") 
          }}
        delay_off: "00:10:00"
        icon_template: >
          {% if is_state("binary_sensor.outside_motion", "on") %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}
  - platform: tod
    name: Morning mood lights
    after: '05:00'
    before: sunrise
  - platform: tod
    name: Evening mood lights
    after: sunset
    before: '23:00'

  - platform: mqtt
    name: 'House doorbell'
    state_topic: 'house/groundfloor/technical/binary_sensor/doorbell/state'
    unique_id: 'house/groundfloor/technical/binary_sensor/doorbell'
    availability_topic: 'house/groundfloor/technical/status'
    

media_player:
  - platform: kodi
    name: Cyril
    host: !secret cyril_host
  - platform: snapcast
    host: !secret media_host
  - platform: mpd
    host: !secret media_host
    name: webPlayer

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_group
      - !secret telegram_joeri

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_group
  - name: cyril
    platform: kodi
    host: !secret cyril_host
  - name: default
    platform: group
    services:
      - service: telegram
      - service: cyril
#      - service: notify
    
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://hass:9541
    
climate:
  - platform: generic_thermostat
    name: Central Heating
    heater: switch.thermostat_switch
    target_sensor: sensor.apartment_temperature #sensor.tv_temperature
    min_temp: 15
    max_temp: 28
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 1
    initial_hvac_mode: 'heat'
    target_temp: 20
    away_temp: 18

rest_command:
  mplayer:
    url: !secret mplayer_command_url
    method: POST
    payload: '{"cmd": "{{ cmd }}", "file": "{{ file }}", "value": "{{ value }}"}'
    content_type:  'application/json; charset=utf-8'

input_boolean:
  notify_camera_movement:
    name: Notify when there is movement on a camera
    icon: mdi:cctv
    
shell_command:
  turn_off_colman_pc: "ssh 10.163.205.12 touch haTest"

