# climate living
- platform: min_max
  name: 'Living temperature'
  type: mean
  entity_ids:
    #- sensor.tv_temperature
    - sensor.living_mobile_temperature
    - sensor.bookshelf_temperature
  #icon: mdi:Thermometer
  #unique_id: 'app/living/global/sensor/temperature'

- platform: min_max
  name: 'Living humidity'
  type: mean
  entity_ids:
    #- sensor.tv_humidity
    - sensor.living_mobile_humidity
    - sensor.bookshelf_humidity
  #icon: mdi:WaterPercent
  #unique_id: 'app/living/global/sensor/humidity'

- platform: min_max
  name: 'Apartment temperature'
  type: mean
  entity_ids:
    #- sensor.tv_temperature
    - sensor.living_mobile_temperature
    - sensor.bookshelf_temperature
    - sensor.kitchen_mobile_temperature
    - sensor.badroom_mobile_temperature
    - sensor.kidroom_mobile_temperature

- platform: min_max
  name: 'Apartment humidity'
  type: mean
  entity_ids:
    #- sensor.tv_humidity
    - sensor.living_mobile_humidity
    - sensor.bookshelf_humidity
    - sensor.kitchen_mobile_humidity
    - sensor.badroom_mobile_humidity
    - sensor.kidroom_mobile_humidity
    
# climate tv
- platform: mqtt
  name: 'TV temperature'
  unique_id: 'app/living/tv/sensor/temperature'
  value_template: '{{ value_json.temperature | round(1) }}'
  state_topic: 'home/living/tv/sensor/dht'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'TV humidity'
  unique_id: 'app/living/tv/sensor/humidity'
  value_template: '{{ value_json.humidity | round(1) }}'
  state_topic: 'home/living/tv/sensor/dht'
  device_class: humidity
  unit_of_measurement: '%'

# climate bookshelf
- platform: mqtt
  name: 'Bookshelf temperature'
  unique_id: 'app/living/bookshelf/sensor/temperature'
  state_topic: 'app/living/bookshelf/sensor/temperature/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Bookshelf humidity'
  unique_id: 'app/living/bookshelf/sensor/humidity'
  state_topic: 'app/living/bookshelf/sensor/humidity/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Bookshelf wifi signal'
  unique_id: 'app/living/bookshelf/sensor/wifi_signal'
  state_topic: 'app/living/bookshelf/sensor/wifi_signal/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: signal_strength
  unit_of_measurement: 'dB'
  
- platform: mqtt
  name: 'Bookshelf uptime'
  unique_id: 'app/living/bookshelf/sensor/uptime'
  state_topic: 'app/living/bookshelf/sensor/uptime/state'
  availability_topic: 'app/living/bookshelf/status'
  unit_of_measurement: 's'
  
# climate living mobile
- platform: mqtt
  name: 'Living mobile temperature'
  unique_id: 'app/living/bookshelf/sensor/living_mobile_temperature'
  state_topic: 'app/living/bookshelf/sensor/living_mobile_temperature/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Living mobile humidity'
  unique_id: 'app/living/bookshelf/sensor/living_mobile_humidity'
  state_topic: 'app/living/bookshelf/sensor/living_mobile_humidity/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Living mobile battery level'
  unique_id: 'app/living/bookshelf/sensor/living_mobile_battery_level'
  state_topic: 'app/living/bookshelf/sensor/living_mobile_battery_level/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: battery
  unit_of_measurement: '%'
  
# climate kitchen mobile
- platform: mqtt
  name: 'Kitchen mobile temperature'
  unique_id: 'app/living/bookshelf/sensor/kitchen_mobile_temperature'
  state_topic: 'app/living/bookshelf/sensor/kitchen_mobile_temperature/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Kitchen mobile humidity'
  unique_id: 'app/living/bookshelf/sensor/kitchen_mobile_humidity'
  state_topic: 'app/living/bookshelf/sensor/kitchen_mobile_humidity/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Kitchen mobile battery level'
  unique_id: 'app/living/bookshelf/sensor/kitchen_mobile_battery_level'
  state_topic: 'app/living/bookshelf/sensor/kitchen_mobile_battery_level/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: battery
  unit_of_measurement: '%'

# climate storage mobile
- platform: mqtt
  name: 'Storage mobile temperature'
  unique_id: 'app/living/bookshelf/sensor/storage_mobile_temperature'
  state_topic: 'app/living/bookshelf/sensor/storage_mobile_temperature/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Storage mobile humidity'
  unique_id: 'app/living/bookshelf/sensor/storage_mobile_humidity'
  state_topic: 'app/living/bookshelf/sensor/storage_mobile_humidity/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Storage mobile battery level'
  unique_id: 'app/living/bookshelf/sensor/storage_mobile_battery_level'
  state_topic: 'app/living/bookshelf/sensor/storage_mobile_battery_level/state'
  availability_topic: 'app/living/bookshelf/status'
  device_class: battery
  unit_of_measurement: '%'
  
  
  
# bedroom control center
- platform: mqtt
  name: 'Bedroom control wifi signal'
  unique_id: 'app/bedroom/control/sensor/wifi_signal'
  state_topic: 'app/bedroom/control/sensor/wifi_signal/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: signal_strength
  unit_of_measurement: 'dB'
  
- platform: mqtt
  name: 'Bedroom control uptime'
  unique_id: 'app/bedroom/control/sensor/uptime'
  state_topic: 'app/bedroom/control/sensor/uptime/state'
  availability_topic: 'app/bedroom/control/status'
  unit_of_measurement: 's'
  
  # climate bedroom mobile
- platform: mqtt
  name: 'Bedroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/bedroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/bedroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Bedroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/bedroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/bedroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Bedroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/bedroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/bedroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate badroom mobile
- platform: mqtt
  name: 'Badroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/badroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/badroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Badroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/badroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/badroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Badroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/badroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/badroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate kidroom mobile
- platform: mqtt
  name: 'Kidroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/kidroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/kidroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Kidroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/kidroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/kidroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Kidroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/kidroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/kidroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate sportroom mobile
- platform: mqtt
  name: 'Sportroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/sportroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/sportroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Sportroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/sportroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/sportroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Sportroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/sportroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/sportroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate hall mobile
- platform: mqtt
  name: 'Hall mobile temperature'
  unique_id: 'app/bedroom/control/sensor/hall_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/hall_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Hall mobile humidity'
  unique_id: 'app/bedroom/control/sensor/hall_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/hall_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Hall mobile battery level'
  unique_id: 'app/bedroom/control/sensor/hall_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/hall_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  
  
  
# house first floor metrics
- platform: mqtt
  name: 'First floor control wifi signal'
  unique_id: 'house/firstfloor/sensor/wifi_signal'
  state_topic: 'house/firstfloor/sensor/wifi_signal/state'
  availability_topic: 'house/firstfloor/status'
  device_class: signal_strength
  unit_of_measurement: 'dB'
  
- platform: mqtt
  name: 'First floor control uptime'
  unique_id: 'house/firstfloor/sensor/uptime'
  state_topic: 'house/firstfloor/sensor/uptime/state'
  availability_topic: 'house/firstfloor/status'
  unit_of_measurement: 's'
  
  # climate hallway mobile
- platform: mqtt
  name: 'Hallway mobile temperature'
  unique_id: 'house/firstfloor/sensor/hallway_mobile_temperature'
  state_topic: 'house/firstfloor/sensor/hallway_mobile_temperature/state'
  availability_topic: 'house/firstfloor/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Hallway mobile humidity'
  unique_id: 'house/firstfloor/sensor/hallway_mobile_humidity'
  state_topic: 'house/firstfloor/sensor/hallway_mobile_humidity/state'
  availability_topic: 'house/firstfloor/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Hallway mobile battery level'
  unique_id: 'house/firstfloor/sensor/hallway_mobile_battery_level'
  state_topic: 'house/firstfloor/sensor/hallway_mobile_battery_level/state'
  availability_topic: 'house/firstfloor/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate technical mobile
- platform: mqtt
  name: 'Technical mobile temperature'
  unique_id: 'house/firstfloor/sensor/technical_mobile_temperature'
  state_topic: 'house/firstfloor/sensor/technical_mobile_temperature/state'
  availability_topic: 'house/firstfloor/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Technical mobile humidity'
  unique_id: 'house/firstfloor/sensor/technical_mobile_humidity'
  state_topic: 'house/firstfloor/sensor/technical_mobile_humidity/state'
  availability_topic: 'house/firstfloor/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Technical mobile battery level'
  unique_id: 'house/firstfloor/sensor/technical_mobile_battery_level'
  state_topic: 'house/firstfloor/sensor/technical_mobile_battery_level/state'
  availability_topic: 'house/firstfloor/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate room 2 mobile
- platform: mqtt
  name: 'Room 2 mobile temperature'
  unique_id: 'house/firstfloor/sensor/room_2_mobile_temperature'
  state_topic: 'house/firstfloor/sensor/room_2_mobile_temperature/state'
  availability_topic: 'house/firstfloor/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Room 2 mobile humidity'
  unique_id: 'house/firstfloor/sensor/room_2_mobile_humidity'
  state_topic: 'house/firstfloor/sensor/room_2_mobile_humidity/state'
  availability_topic: 'house/firstfloor/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Room 2 mobile battery level'
  unique_id: 'house/firstfloor/sensor/room_2_mobile_battery_level'
  state_topic: 'house/firstfloor/sensor/room_2_mobile_battery_level/state'
  availability_topic: 'house/firstfloor/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate office mobile
- platform: mqtt
  name: 'Office mobile temperature'
  unique_id: 'house/firstfloor/sensor/office_mobile_temperature'
  state_topic: 'house/firstfloor/sensor/office_mobile_temperature/state'
  availability_topic: 'house/firstfloor/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Office mobile humidity'
  unique_id: 'house/firstfloor/sensor/office_mobile_humidity'
  state_topic: 'house/firstfloor/sensor/office_mobile_humidity/state'
  availability_topic: 'house/firstfloor/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Office mobile battery level'
  unique_id: 'house/firstfloor/sensor/office_mobile_battery_level'
  state_topic: 'house/firstfloor/sensor/office_mobile_battery_level/state'
  availability_topic: 'house/firstfloor/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate room_4 mobile
- platform: mqtt
  name: 'Room 4 mobile temperature'
  unique_id: 'house/firstfloor/sensor/room_4_mobile_temperature'
  state_topic: 'house/firstfloor/sensor/room_4_mobile_temperature/state'
  availability_topic: 'house/firstfloor/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Room 4 mobile humidity'
  unique_id: 'house/firstfloor/sensor/room_4_mobile_humidity'
  state_topic: 'house/firstfloor/sensor/room_4_mobile_humidity/state'
  availability_topic: 'house/firstfloor/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Room 4 mobile battery level'
  unique_id: 'house/firstfloor/sensor/room_4_mobile_battery_level'
  state_topic: 'house/firstfloor/sensor/room_4_mobile_battery_level/state'
  availability_topic: 'house/firstfloor/status'
  device_class: battery
  unit_of_measurement: '%'
  
  # climate badroom firstfloor mobile
- platform: mqtt
  name: 'Badroom firstfloor mobile temperature'
  unique_id: 'house/firstfloor/sensor/badroom_mobile_temperature'
  state_topic: 'house/firstfloor/sensor/badroom_mobile_temperature/state'
  availability_topic: 'house/firstfloor/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Badroom firstfloor mobile humidity'
  unique_id: 'house/firstfloor/sensor/badroom_mobile_humidity'
  state_topic: 'house/firstfloor/sensor/badroom_mobile_humidity/state'
  availability_topic: 'house/firstfloor/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Badroom firstfloor mobile battery level'
  unique_id: 'house/firstfloor/sensor/badroom_mobile_battery_level'
  state_topic: 'house/firstfloor/sensor/badroom_mobile_battery_level/state'
  availability_topic: 'house/firstfloor/status'
  device_class: battery
  unit_of_measurement: '%'

  
  
# nmbs
#- platform: nmbs
#  station_from: 'Deinze'
#  station_to: 'Gent-Sint-Pieters'
#  station_live: 'Deinze'

- platform: mqtt
  name: 'Kitchen button'
  state_topic: 'app/kitchen/wall/sensor/button/state'
  unique_id: 'app/kitchen/wall/sensor/button'
  availability_topic: 'app/kitchen/wall/status'
  expire_after: 3
  
- platform: mqtt
  name: 'House doorbell'
  state_topic: 'house/groundfloor/technical/sensor/doorbell/state'
  unique_id: 'house/groundfloor/technical/sensor/doorbell'
  availability_topic: 'house/groundfloor/technical/status'
  expire_after: 3
  
# washer power consumption
- platform: mqtt
  name: 'Washing machine power'
  state_topic: 'house/groundfloor/technical/sensor/washer_power/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_power'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'W'
  device_class: power
- platform: mqtt
  name: 'Washing machine current'
  state_topic: 'house/groundfloor/technical/sensor/washer_current/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_current'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'A'
  device_class: power
- platform: mqtt
  name: 'Washing machine voltage'
  state_topic: 'house/groundfloor/technical/sensor/washer_voltage/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_voltage'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'V'
  device_class: power
- platform: mqtt
  name: 'Washing machine total'
  state_topic: 'house/groundfloor/technical/sensor/washer_total/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_total'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'kWh'
  device_class: power
  
  
- platform: mqtt
  name: 'cctv motion detection'
  state_topic: 'cctv/detect'
  unique_id: 'cctv/detect'
  expire_after: 3
  

- platform: mqtt
  name: 'Backup status'
  unique_id: 'infra/backup/status'
  state_topic: 'infra/backup/status'


