- platform: mqtt
  schema: json
  name: 'Kitchen wall'
  unique_id: 'app/kitchen/wall/light/wall'
  state_topic: 'app/kitchen/wall/light/wall/state'
  command_topic: 'app/kitchen/wall/light/wall/command'
  availability_topic: 'app/kitchen/wall/status'
  brightness: true
  effect: true
  effect_list: [strobe, flicker]
  optimistic: false
  qos: 0
  
#- platform: mqtt
#  schema: json
#  name: 'TV backlight'
#  unique_id: 'app/living/tv/light/back'
#  state_topic: 'app/living/tv/light/back'
#  command_topic: 'app/living/tv/light/back/set'
#  brightness: true
#  rgb: true
#  effect: true
#  effect_list: [colorfade_slow, colorfade_fast, flash]
#  optimistic: false
#  qos: 0

- platform: mqtt
  schema: json
  name: 'Bookshelf'
  unique_id: 'app/living/bookshelf/light/center'
  state_topic: 'app/living/bookshelf/light/center/state'
  command_topic: 'app/living/bookshelf/light/center/command'
  availability_topic: 'app/living/bookshelf/status'
  brightness: true
  rgb: true
  effect: true
  effect_list: [random, strobe, flicker]
  optimistic: false
  qos: 0
