- platform: mqtt
  schema: json
  name: 'Bedroom Ruben'
  unique_id: 'house/firstfloor/light/bedroom'
  state_topic: 'house/firstfloor/light/bedroom/state'
  command_topic: 'house/firstfloor/light/bedroom/command'
  availability_topic: 'house/firstfloor/status'
  optimistic: false
  qos: 0
- platform: mqtt
  schema: json
  name: 'Bedroom Ruben dressing'
  unique_id: 'house/firstfloor/light/bedroom_dressing'
  state_topic: 'house/firstfloor/light/bedroom_dressing/state'
  command_topic: 'house/firstfloor/light/bedroom_dressing/command'
  availability_topic: 'house/firstfloor/status'
  optimistic: false
  qos: 0
  
  