- platform: min_max
  name: 'Livingroom 02 temperature'
  type: mean
  entity_ids:
    - sensor.livingroom_02_mobile_temperature
    - sensor.livingroom_02_bookshelf_temperature
    - sensor.kitchen_02_mobile_temperature

- platform: min_max
  name: 'Livingroom 02 humidity'
  type: mean
  entity_ids:
    - sensor.livingroom_02_mobile_humidity
    - sensor.livingroom_02_bookshelf_humidity
    - sensor.kitchen_02_mobile_humidity

- platform: min_max
  name: 'Apartment temperature'
  type: mean
  entity_ids:
    - sensor.livingroom_02_mobile_temperature
    - sensor.livingroom_02_bookshelf_temperature
    - sensor.kitchen_02_mobile_temperature
    - sensor.badroom_03_mobile_temperature
    - sensor.bedroom_05_mobile_temperature
    - sensor.bedroom_06_mobile_temperature
    - sensor.bedroom_07_mobile_temperature
    - sensor.entry_03_mobile_temperature
    - sensor.storage_mobile_temperature

- platform: min_max
  name: 'Apartment humidity'
  type: mean
  entity_ids:
    - sensor.livingroom_02_mobile_humidity
    - sensor.livingroom_02_bookshelf_humidity
    - sensor.kitchen_02_mobile_humidity
    - sensor.badroom_03_mobile_humidity
    - sensor.bedroom_05_mobile_humidity
    - sensor.bedroom_06_mobile_humidity
    - sensor.bedroom_07_mobile_humidity
    - sensor.entry_03_mobile_humidity
    - sensor.storage_mobile_humidity
    