# climate living
- platform: min_max
  name: 'Living temperature'
  type: mean
  entity_ids:
    #- sensor.tv_temperature
    - sensor.livingroom_02_mobile_temperature
    - sensor.livingroom_02_bookshelf_temperature

- platform: min_max
  name: 'Living humidity'
  type: mean
  entity_ids:
    #- sensor.tv_humidity
    - sensor.livingroom_02_mobile_humidity
    - sensor.livingroom_02_bookshelf_humidity

- platform: min_max
  name: 'Apartment temperature'
  type: mean
  entity_ids:
    - sensor.livingroom_02_mobile_temperature
    - sensor.livingroom_02_bookshelf_temperature
    - sensor.kitchen_02_mobile_temperature
    - sensor.badroom_mobile_temperature
    - sensor.kidroom_mobile_temperature

- platform: min_max
  name: 'Apartment humidity'
  type: mean
  entity_ids:
    - sensor.livingroom_02_mobile_humidity
    - sensor.livingroom_02_bookshelf_humidity
    - sensor.kitchen_02_mobile_humidity
    - sensor.badroom_mobile_humidity
    - sensor.kidroom_mobile_humidity

# climate bookshelf
#- platform: mqtt
#  name: 'Bookshelf temperature'
#  unique_id: 'app/living/bookshelf/sensor/temperature'
#  state_topic: 'app/living/bookshelf/sensor/temperature/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: temperature
#  unit_of_measurement: '°C'
#  state_class: measurement

#- platform: mqtt
#  name: 'Bookshelf humidity'
#  unique_id: 'app/living/bookshelf/sensor/humidity'
#  state_topic: 'app/living/bookshelf/sensor/humidity/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: humidity
#  unit_of_measurement: '%'
#  state_class: measurement
  
#- platform: mqtt
#  name: 'Bookshelf wifi signal'
#  unique_id: 'app/living/bookshelf/sensor/wifi_signal'
#  state_topic: 'app/living/bookshelf/sensor/wifi_signal/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: signal_strength
#  unit_of_measurement: 'dB'
#  state_class: measurement
  
#- platform: mqtt
#  name: 'Bookshelf uptime'
#  unique_id: 'app/living/bookshelf/sensor/uptime'
#  state_topic: 'app/living/bookshelf/sensor/uptime/state'
#  availability_topic: 'app/living/bookshelf/status'
#  unit_of_measurement: 's'
#  state_class: measurement
  
# climate living mobile
#- platform: mqtt
#  name: 'Living mobile temperature'
#  unique_id: 'app/living/bookshelf/sensor/living_mobile_temperature'
#  state_topic: 'app/living/bookshelf/sensor/living_mobile_temperature/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: temperature
#  unit_of_measurement: '°C'
#  state_class: measurement

#- platform: mqtt
#  name: 'Living mobile humidity'
#  unique_id: 'app/living/bookshelf/sensor/living_mobile_humidity'
#  state_topic: 'app/living/bookshelf/sensor/living_mobile_humidity/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: humidity
#  unit_of_measurement: '%'
#  state_class: measurement
  
#- platform: mqtt
#  name: 'Living mobile battery level'
#  unique_id: 'app/living/bookshelf/sensor/living_mobile_battery_level'
#  state_topic: 'app/living/bookshelf/sensor/living_mobile_battery_level/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: battery
#  unit_of_measurement: '%'
#  state_class: measurement
  
# climate kitchen mobile
#- platform: mqtt
#  name: 'Kitchen mobile temperature'
#  unique_id: 'app/living/bookshelf/sensor/kitchen_mobile_temperature'
#  state_topic: 'app/living/bookshelf/sensor/kitchen_mobile_temperature/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: temperature
#  unit_of_measurement: '°C'
#  state_class: measurement

#- platform: mqtt
#  name: 'Kitchen mobile humidity'
#  unique_id: 'app/living/bookshelf/sensor/kitchen_mobile_humidity'
#  state_topic: 'app/living/bookshelf/sensor/kitchen_mobile_humidity/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: humidity
#  unit_of_measurement: '%'
#  state_class: measurement
  
#- platform: mqtt
#  name: 'Kitchen mobile battery level'
#  unique_id: 'app/living/bookshelf/sensor/kitchen_mobile_battery_level'
#  state_topic: 'app/living/bookshelf/sensor/kitchen_mobile_battery_level/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: battery
#  unit_of_measurement: '%'
#  state_class: measurement

# climate storage mobile
#- platform: mqtt
#  name: 'Storage mobile temperature'
#  unique_id: 'app/living/bookshelf/sensor/storage_mobile_temperature'
#  state_topic: 'app/living/bookshelf/sensor/storage_mobile_temperature/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: temperature
#  unit_of_measurement: '°C'
#  state_class: measurement

#- platform: mqtt
#  name: 'Storage mobile humidity'
#  unique_id: 'app/living/bookshelf/sensor/storage_mobile_humidity'
#  state_topic: 'app/living/bookshelf/sensor/storage_mobile_humidity/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: humidity
#  unit_of_measurement: '%'
#  state_class: measurement
  
#- platform: mqtt
#  name: 'Storage mobile battery level'
#  unique_id: 'app/living/bookshelf/sensor/storage_mobile_battery_level'
#  state_topic: 'app/living/bookshelf/sensor/storage_mobile_battery_level/state'
#  availability_topic: 'app/living/bookshelf/status'
#  device_class: battery
#  unit_of_measurement: '%'
#  state_class: measurement
  
  
  
# bedroom control center
- platform: mqtt
  name: 'Bedroom control wifi signal'
  unique_id: 'app/bedroom/control/sensor/wifi_signal'
  state_topic: 'app/bedroom/control/sensor/wifi_signal/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: signal_strength
  unit_of_measurement: 'dB'
  state_class: measurement
  
- platform: mqtt
  name: 'Bedroom control uptime'
  unique_id: 'app/bedroom/control/sensor/uptime'
  state_topic: 'app/bedroom/control/sensor/uptime/state'
  availability_topic: 'app/bedroom/control/status'
  unit_of_measurement: 's'
  state_class: measurement
  
  # climate bedroom mobile
- platform: mqtt
  name: 'Bedroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/bedroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/bedroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'
  state_class: measurement

- platform: mqtt
  name: 'Bedroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/bedroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/bedroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  state_class: measurement
  
- platform: mqtt
  name: 'Bedroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/bedroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/bedroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  state_class: measurement
  
  # climate badroom mobile
- platform: mqtt
  name: 'Badroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/badroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/badroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'
  state_class: measurement

- platform: mqtt
  name: 'Badroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/badroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/badroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  state_class: measurement
  
- platform: mqtt
  name: 'Badroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/badroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/badroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  state_class: measurement
  
  # climate kidroom mobile
- platform: mqtt
  name: 'Kidroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/kidroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/kidroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'
  state_class: measurement

- platform: mqtt
  name: 'Kidroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/kidroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/kidroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  state_class: measurement
  
- platform: mqtt
  name: 'Kidroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/kidroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/kidroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  state_class: measurement
  
  # climate sportroom mobile
- platform: mqtt
  name: 'Sportroom mobile temperature'
  unique_id: 'app/bedroom/control/sensor/sportroom_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/sportroom_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'
  state_class: measurement

- platform: mqtt
  name: 'Sportroom mobile humidity'
  unique_id: 'app/bedroom/control/sensor/sportroom_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/sportroom_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  
- platform: mqtt
  name: 'Sportroom mobile battery level'
  unique_id: 'app/bedroom/control/sensor/sportroom_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/sportroom_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  state_class: measurement
  
  # climate hall mobile
- platform: mqtt
  name: 'Hall mobile temperature'
  unique_id: 'app/bedroom/control/sensor/hall_mobile_temperature'
  state_topic: 'app/bedroom/control/sensor/hall_mobile_temperature/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: temperature
  unit_of_measurement: '°C'
  state_class: measurement

- platform: mqtt
  name: 'Hall mobile humidity'
  unique_id: 'app/bedroom/control/sensor/hall_mobile_humidity'
  state_topic: 'app/bedroom/control/sensor/hall_mobile_humidity/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: humidity
  unit_of_measurement: '%'
  state_class: measurement
  
- platform: mqtt
  name: 'Hall mobile battery level'
  unique_id: 'app/bedroom/control/sensor/hall_mobile_battery_level'
  state_topic: 'app/bedroom/control/sensor/hall_mobile_battery_level/state'
  availability_topic: 'app/bedroom/control/status'
  device_class: battery
  unit_of_measurement: '%'
  state_class: measurement
  
