#- platform: mqtt
#  name: 'Kitchen wifi signal'
#  unique_id: 'app/kitchen/wall/sensor/wifi_signal'
#  state_topic: 'app/kitchen/wall/sensor/wifi_signal/state'
#  availability_topic: 'app/kitchen/wall/status'
#  device_class: signal_strength
#  unit_of_measurement: 'dB'
  
#- platform: mqtt
#  name: 'Kitchen uptime'
#  unique_id: 'app/kitchen/wall/sensor/uptime'
#  state_topic: 'app/kitchen/wall/sensor/uptime/state'
#  availability_topic: 'app/kitchen/wall/status'
#  unit_of_measurement: 's'
  
#- platform: mqtt
#  name: 'Kitchen button'
#  state_topic: 'app/kitchen/wall/sensor/button/state'
#  unique_id: 'app/kitchen/wall/sensor/button'
#  availability_topic: 'app/kitchen/wall/status'
#  expire_after: 3  
  
- platform: mqtt
  name: 'cctv motion detection'
  state_topic: 'cctv/detect'
  unique_id: 'cctv/detect'
  expire_after: 3
  

- platform: mqtt
  name: 'Backup status'
  unique_id: 'infra/backup/status'
  state_topic: 'infra/backup/status'

#- platform: nmbs
#  station_from: 'Deinze'
#  station_to: 'Gent-Sint-Pieters'
#  station_live: 'Deinze'

- platform: mqtt
  name: 'Server temperature'
  unique_id: 'home/entry/gate/front/temp'
  state_topic: 'home/entry/gate/front/temp'
  availability_topic: 'home/entry/gate/front/status'
  device_class: temperature
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Server humidity'
  unique_id: 'home/entry/gate/front/humid'
  state_topic: 'home/entry/gate/front/humid'
  availability_topic: 'home/entry/gate/front/status'
  device_class: humidity
  unit_of_measurement: '%'
  
  