
#- platform: mqtt
#  name: 'House doorbell'
#  state_topic: 'house/groundfloor/technical/sensor/doorbell/state'
#  unique_id: 'house/groundfloor/technical/sensor/doorbell'
#  availability_topic: 'house/groundfloor/technical/status'
#  expire_after: 3
  
  
# ground floor control center
- platform: mqtt
  name: 'Ground floor technical wifi signal'
  unique_id: 'house/groundfloor/technical/sensor/wifi_signal'
  state_topic: 'house/groundfloor/technical/sensor/wifi_signal/state'
  availability_topic: 'house/groundfloor/technical/status'
  device_class: signal_strength
  unit_of_measurement: 'dB'
  
- platform: mqtt
  name: 'Ground floor technical uptime'
  unique_id: 'house/groundfloor/technical/sensor/uptime'
  state_topic: 'house/groundfloor/technical/sensor/uptime/state'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 's'
  
# washer power consumption
- platform: mqtt
  name: 'Washing machine power'
  state_topic: 'house/groundfloor/technical/sensor/washer_power/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_power'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'W'
  device_class: power
- platform: mqtt
  name: 'Washing machine current'
  state_topic: 'house/groundfloor/technical/sensor/washer_current/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_current'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'A'
  device_class: power
- platform: mqtt
  name: 'Washing machine voltage'
  state_topic: 'house/groundfloor/technical/sensor/washer_voltage/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_voltage'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'V'
  device_class: power
- platform: mqtt
  name: 'Washing machine total'
  state_topic: 'house/groundfloor/technical/sensor/washer_total/state'
  unique_id: 'house/groundfloor/technical/sensor/washer_total'
  availability_topic: 'house/groundfloor/technical/status'
  unit_of_measurement: 'kWh'
  device_class: power
