wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: !secret wifi_password
  
captive_portal:

# Enable logging
logger:

#web_server:
#  port: 80

#api:
#  password: !secret device_password

ota:
  password: !secret device_password

sensor:
  - <<: !include sensor/uptime.yaml
  - <<: !include sensor/wifi_signal.yaml
