esphome:
  name: app_living_bookshelf
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "App Living Bookshelf New"
    password: "jzDio0zQrD5Z"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "app/living/bookshelf"
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: !secret device_password

ota:
  password: !secret device_password


sensor:
  - platform: uptime
    name: "Uptime"
    
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    
  - platform: dht
    pin: GPIO26
    temperature:
      name: "Temperature"  
      filters:
        - filter_out: nan
    humidity:
      name: "Humidity"
      filters:
        - filter_out: nan
    update_interval: 30s
    model: DHT22

  #ATC_06BFCB
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:06:BF:CB
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Living Mobile Temperature"
    humidity:
      name: "Living Mobile Humidity"
    battery_level:
      name: "Living Mobile Battery Level"
      
  #ATC_E5A904
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:E5:A9:04
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Kitchen Mobile Temperature"
    humidity:
      name: "Kitchen Mobile Humidity"
    battery_level:
      name: "Kitchen Mobile Battery Level"

  #ATC_BB7E23
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:BB:7E:23
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Storage Mobile Temperature"
    humidity:
      name: "Storage Mobile Humidity"
    battery_level:
      name: "Storage Mobile Battery Level"
  
    
light:
  - platform: rgb
    id: center
    name: "Center"
    red: out_l_r
    green: out_l_g
    blue: out_l_b
    effects:
      - random:
      - strobe:
      - flicker:
      
# Example output entry
output:
  - platform: ledc
    id: out_l_r
    pin: GPIO21
  - platform: ledc
    id: out_l_g
    pin: GPIO17
  - platform: ledc
    id: out_l_b
    pin: GPIO16

status_led:
  pin:
    number: GPIO2
    inverted: False
  
esp32_ble_tracker:

