substitutions:
  devicename: app_living_bookshelf
  topic: 'app/living/bookshelf'
  
packages:
  device_base: !include common/esp32.yaml

<<: !include common/mqtt.yaml

esp32_ble_tracker:

sensor:
  - platform: dht
    pin: GPIO26
    temperature:
      name: "Temperature"  
      filters:
        - filter_out: nan
    humidity:
      name: "Humidity"
      filters:
        - filter_out: nan
    update_interval: 30s
    model: DHT22

  #ATC_06BFCB
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:06:BF:CB
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Living Mobile Temperature"
    humidity:
      name: "Living Mobile Humidity"
    battery_level:
      name: "Living Mobile Battery Level"
      
  #ATC_E5A904
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:E5:A9:04
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Kitchen Mobile Temperature"
    humidity:
      name: "Kitchen Mobile Humidity"
    battery_level:
      name: "Kitchen Mobile Battery Level"

  #ATC_BB7E23
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:BB:7E:23
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Storage Mobile Temperature"
    humidity:
      name: "Storage Mobile Humidity"
    battery_level:
      name: "Storage Mobile Battery Level"

light:
  - platform: rgb
    id: center
    name: "Center"
    red: out_l_r
    green: out_l_g
    blue: out_l_b
    effects:
      - random:
      - strobe:
      - flicker:

# Example output entry
output:
  - platform: ledc
    id: out_l_r
    pin: GPIO21
  - platform: ledc
    id: out_l_g
    pin: GPIO17
  - platform: ledc
    id: out_l_b
    pin: GPIO16
