substitutions:
  devicename: app_bedroom_control
  topic: 'app/bedroom/control'

packages:
  device_base: !include common/esp32.yaml

esp32_ble_tracker:

sensor:
  #ATC_D82F9C
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:D8:2F:9C
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Bedroom Mobile Temperature"
    humidity:
      name: "Bedroom Mobile Humidity"
    battery_level:
      name: "Bedroom Mobile Battery Level"
        
  #ATC_84A994
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:84:A9:94
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Badroom Mobile Temperature"
    humidity:
      name: "Badroom Mobile Humidity"
    battery_level:
      name: "Badroom Mobile Battery Level"
      
  #ATC_414283
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:41:42:83
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Kidroom Mobile Temperature"
    humidity:
      name: "Kidroom Mobile Humidity"
    battery_level:
      name: "Kidroom Mobile Battery Level"
      
  #ATC_DD8395
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:DD:83:95
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Sportroom Mobile Temperature"
    humidity:
      name: "Sportroom Mobile Humidity"
    battery_level:
      name: "Sportroom Mobile Battery Level"
      
  #ATC_FCF692
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:FC:F6:92
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Hall Mobile Temperature"
    humidity:
      name: "Hall Mobile Humidity"
    battery_level:
      name: "Hall Mobile Battery Level"
