esphome:
  name: app_kitchen_wall
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "App Kitchen Wall"
    password: "jzDio0zQrD5Z"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "app/kitchen/wall"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: !secret device_password

ota:
  password: !secret device_password

#sensor:
#  - platform: dht
#    pin: GPIO16
#    temperature:
#      name: "Living Room Bookshelf Temperature"
#    humidity:
#      name: "Living Room Bookshelf Humidity"
#    update_interval: 30s
#    model: DHT22

light:
  - platform: monochromatic
    id: wall
    name: "Wall"
    output: out_l
    effects:
      - strobe:
      - flicker:
      

# Example output entry
output:
  - platform: esp8266_pwm
    id: out_l
    pin: GPIO14

status_led:
  pin:
    number: GPIO2
    inverted: True


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "Button"
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - mqtt.publish:
            topic: app/kitchen/wall/button
            payload: 2
    - timing:
        - ON for 1s to 2s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - mqtt.publish:
            topic: app/kitchen/wall/button
            payload: -1
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - light.toggle: wall
        - mqtt.publish:
            topic: app/kitchen/wall/button
            payload: 1
      