substitutions:
  devicename: bedroom-01-dressing-power
  displayname: 'Bedroom 01 dressing power'

packages:
  device_base: !include common/esp32.yaml

external_components:
  - source: github://depuits/esphome-SDM-enery-meter

# Disable logging
logger:
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: sdm
    dere_pin: 16
    baud_rate: 9600
    channel: 1
    sdm_phase_1_voltage:
      name: "Washer voltage"
    sdm_phase_1_current:
      name: "Washer current"
    sdm_phase_1_power:
      name: "Washer power"
    sdm_total_active_energy:
      name: "Washer total"

#  - platform: AButt
#    name: "Doorbell"
#    retain: False
#    inverted: True
#    pin: 27

binary_sensor:
  - platform: gpio
    name: "Entry 01 doorbell"
    pin:
      number: GPIO27
      inverted: True
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
