substitutions:
  devicename: bedroom-01-dressing-power
  displayname: 'Bedroom 01 dressing power'

packages:
  device_base: !include common/esp32.yaml

# Disable logging
logger:
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: 16
  
sensor:
  - platform: sdm_meter
    phase_a:
      current:
        name: "Washer current"
      voltage:
        name: "Washer voltage"
      active_power:
        name: "Washer power"
    import_active_energy:
      name: "Washer total"
    update_interval: 15s

binary_sensor:
  - platform: gpio
    name: "Entry 01 doorbell"
    pin:
      number: GPIO27
      inverted: True
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
