substitutions:
  devicename: bedroom-06-control
  displayname: 'Bedroom 06 control'

packages:
  device_base: !include common/esp32.yaml

esp32_ble_tracker:

sensor:
  #ATC_D82F9C
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:D8:2F:9C
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Bedroom 05 mobile temperature"
    humidity:
      name: "Bedroom 05 mobile humidity"
    battery_level:
      name: "Bedroom 05 mobile battery level"
        
  #ATC_84A994
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:84:A9:94
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Badroom 03 mobile temperature"
    humidity:
      name: "Badroom 03 mobile humidity"
    battery_level:
      name: "Badroom 03 mobile battery level"
      
  #ATC_414283
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:41:42:83
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Bedroom 06 mobile temperature"
    humidity:
      name: "Bedroom 06 mobile humidity"
    battery_level:
      name: "Bedroom 06 mobile battery level"
      
  #ATC_DD8395
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:DD:83:95
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Bedroom 07 mobile temperature"
    humidity:
      name: "Bedroom 07 mobile humidity"
    battery_level:
      name: "Bedroom 07 mobile battery level"
      
  #ATC_FCF692
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:FC:F6:92
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Entry 03 mobile temperature"
    humidity:
      name: "Entry 03 mobile humidity"
    battery_level:
      name: "Entry 03 mobile battery level"
