substitutions:
  devicename: garage-01-power
  displayname: 'Garage 01 power'

packages:
  device_base: !include common/esp32.yaml

# Disable logging
logger:
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 4800
  stop_bits: 1

modbus:
  flow_control_pin: 16
  
sensor:
  - platform: sdm_meter
    phase_a:
      current:
        name: "Apartment phase 1 current"
      voltage:
        name: "Apartment phase 1 voltage"
      active_power:
        name: "Apartment phase 1 power"
    import_active_energy:
      name: "Apartment total energy"
    update_interval: 15s
    
binary_sensor:
  - platform: gpio
    name: "Entry 03 doorbell"
    pin:
      number: GPIO27
      inverted: True
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
