substitutions:
  devicename: house_firstfloor_control
  topic: 'house/firstfloor'

packages:
  device_base: !include common/esp32.yaml

<<: !include common/mqtt.yaml

external_components:
  - source: github://depuits/esphome-AButt

esp32_ble_tracker:

sensor:
  #ATC_6345A6
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:63:45:A6
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Hallway Mobile Temperature"
    humidity:
      name: "Hallway Mobile Humidity"
    battery_level:
      name: "Hallway Mobile Battery Level"
      
  #ATC_B8A417
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:B8:A4:17
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Technical Mobile Temperature"
    humidity:
      name: "Technical Mobile Humidity"
    battery_level:
      name: "Technical Mobile Battery Level"
    
  #ATC_2F4235
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:2F:42:35
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Room 2 Mobile Temperature"
    humidity:
      name: "Room 2 Mobile Humidity"
    battery_level:
      name: "Room 2 Mobile Battery Level"
      
  #ATC_59AEB8
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:59:AE:B8
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Office Mobile Temperature"
    humidity:
      name: "Office Mobile Humidity"
    battery_level:
      name: "Office Mobile Battery Level"
      
  #ATC_82EEC3
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:82:EE:C3
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Room 4 Mobile Temperature"
    humidity:
      name: "Room 4 Mobile Humidity"
    battery_level:
      name: "Room 4 Mobile Battery Level"
      
  #ATC_13AD3A
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:13:AD:3A
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Badroom Mobile Temperature"
    humidity:
      name: "Badroom Mobile Humidity"
    battery_level:
      name: "Badroom Mobile Battery Level"
    
  #Buttons
  - platform: AButt
    name: "Bedroom button"
    retain: False
    inverted: True
    pin: 22
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == 1;'
            then:
              - light.toggle: bedroom_light
        - if:
            condition:
              lambda: 'return x == 2;'
            then:
              - switch.toggle: bedroom_cover_direction
        - if:
            condition:
              lambda: 'return x == -1;'
            then:
              - switch.turn_on: bedroom_cover_power
        - if:
            condition:
              lambda: 'return x == 0;'
            then:
              - switch.turn_off: bedroom_cover_power

  - platform: AButt
    name: "Bedroom dressing button"
    retain: False
    inverted: True
    pin: 17
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == 1;'
            then:
              - light.toggle: bedroomDressing_light
        - if:
            condition:
              lambda: 'return x == 2;'
            then:
              - light.toggle: bedroom_light
        - if:
            condition:
              lambda: 'return x == -1;'
            then:
              - cover.control:
                  id: bedroom_cover
                  position: 50%

light:
  - platform: binary
    name: "Bedroom"
    output: gpio_lightRoom
    id: bedroom_light
  - platform: binary
    name: "Bedroom dressing"
    output: gpio_lightDressing
    id: bedroomDressing_light

output:
  - platform: gpio
    pin: 
      number: GPIO18
      inverted: True
    id: gpio_lightRoom
  - platform: gpio
    pin: 
      number: GPIO26
      inverted: True
    id: gpio_lightDressing

switch:
  - platform: gpio
    pin: 
      number: GPIO23
      inverted: True
    name: "Bedroom cover power"
    id: bedroom_cover_power
  - platform: gpio
    pin: 
      number: GPIO19
      inverted: True
    name: "Bedroom cover direction"
    id: bedroom_cover_direction

cover:
  - platform: time_based
    name: "Bedroom"
    id: bedroom_cover
    has_built_in_endstop: true 

    open_action:
      - switch.turn_on: bedroom_cover_direction
      - switch.turn_on: bedroom_cover_power
    open_duration: 27s

    close_action:
      - switch.turn_off: bedroom_cover_direction
      - switch.turn_on: bedroom_cover_power
    close_duration: 27s

    stop_action:
      - switch.turn_off: bedroom_cover_power
      - switch.turn_off: bedroom_cover_direction
