substitutions:
  devicename: kitchen-02-wall
  displayname: 'Kitchen 02 wall'

packages:
  device_base: !include common/esp8266.yaml
  
external_components:
  - source: github://depuits/esphome-AButt

light:
  - platform: monochromatic
    id: wall
    name: '${displayname}'
    output: out_l
    effects:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    id: out_l
    pin: GPIO14

sensor:
  - platform: AButt
    name: '${displayname} button'
    pin:
      number: GPIO0
      inverted: True
      mode: INPUT_PULLUP
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == 1;'
            then:
              - light.toggle: wall
        - if:
            condition:
              lambda: 'return x == 2;'
            then:
              - light.turn_on:
                  id: wall
                  brightness: 0.2
        - while:
            condition:
              lambda: 'return x == -1;'
            then:
              - light.dim_relative:
                  id: wall
                  relative_brightness: 1%
                  transition_length: 0.01s
              - delay: 0.05s


#binary_sensor:
#  - platform: gpio
#    pin:
#      number: GPIO0
#      inverted: True
#    name: "Button"
#    on_multi_click:
#    - timing:
#        - ON for at most 1s
#        - OFF for at most 1s
#        - ON for at most 1s
#The inverted binary_sensor property has been replaced by the "
#            "new 'invert' binary  sensor filter. Please see "
#            "https://esphome.io/components/binary_sensor/index.html."        - OFF for at least 0.2s
#      then:
#        - logger.log: "Double Clicked"
#        - mqtt.publish:
#            topic: app/kitchen/wall/button
#            payload: 2
#    - timing:
#        - ON for 1s to 2s
#        - OFF for at least 0.5s
#      then:
#        - logger.log: "Single Long Clicked"
#        - mqtt.publish:
#            topic: app/kitchen/wall/button
#            payload: -1
#    - timing:
#        - ON for at most 1s
#        - OFF for at least 0.5s
#      then:
#        - logger.log: "Single Short Clicked"
#        - light.toggle: wall
#        - mqtt.publish:
#            topic: app/kitchen/wall/button
#            payload: 1
      