substitutions:
  devicename: livingroom-02-tv
  displayname: 'Livingroom 02 tv'

packages:
  device_base: !include common/esp32.yaml

external_components:
  - source: github://depuits/esphome-SDM-enery-meter

# Disable logging
logger:
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: sdm
    dere_pin: 16
    baud_rate: 4800
    channel: 1
    sdm_phase_1_voltage:
      name: "Apartment phase 1 voltage"
    sdm_phase_1_current:
      name: "Apartment phase 1 current"
    sdm_phase_1_power:
      name: "Apartment phase 1 power"
    sdm_total_system_power:
      name: "Apartment total power"
    sdm_total_active_energy:
      name: "Apartment total energy"

#  - platform: AButt
#    name: "Entry 03 doorbell"
#    inverted: True
#    pin: 27

binary_sensor:
  - platform: gpio
    name: "Entry 03 doorbell"
    pin:
      number: GPIO27
      inverted: True
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
