substitutions:
  devicename: livingroom-02-bookshelf
  displayname: 'Livingroom 02 bookshelf'
  
packages:
  device_base: !include common/esp32.yaml

esp32_ble_tracker:

sensor:
  - platform: dht
    pin: GPIO26
    temperature:
      name: "${displayname} temperature"  
      filters:
        - filter_out: nan
    humidity:
      name: "${displayname} humidity"
      filters:
        - filter_out: nan
    update_interval: 30s
    model: DHT22

  #ATC_06BFCB
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:06:BF:CB
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Livingroom 02 mobile temperature"
      id: "livingroom_02_mobile_temperature"
    humidity:
      name: "Livingroom 02 mobile humidity"
    battery_level:
      name: "Livingroom 02 mobile battery level"
      
  #ATC_E5A904
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:E5:A9:04
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Kitchen 02 mobile temperature"
    humidity:
      name: "Kitchen 02 mobile humidity"
    battery_level:
      name: "Kitchen 02 mobile battery level"

  #ATC_BB7E23
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:BB:7E:23
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Storage mobile temperature"
    humidity:
      name: "Storage mobile humidity"
    battery_level:
      name: "Storage mobile battery level"

light:
  - platform: rgb
    name: "${displayname}"
    red: out_l_r
    green: out_l_g
    blue: out_l_b
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: ledc
    id: out_l_r
    pin: GPIO21
  - platform: ledc
    id: out_l_g
    pin: GPIO17
  - platform: ledc
    id: out_l_b
    pin: GPIO16

remote_transmitter:
  pin: GPIO22
  carrier_duty_percent: 50%

climate:
  - platform: fujitsu_general
    name: "Livingroom 02 AC"
    sensor: "livingroom_02_mobile_temperature"
    
